### PR TITLE
[Hacktoberfest] Added IncludeHashEquals annotation as opposed to IgnoreHashEquals.

### LINKED ISSUE #3: Consider annotation to only use a field in the hashcode and equals
Same idea, but the other way around, something like @OnlyHashEquals or @HashEqualsId to only mark the fields to appear in the hashCode and equals. This would be really useful specially when dealing with models that already have an id field so you wouldn't have to put "@IgnoreHashEquals" in all other fields.

@REggar If you agree to include it here I could make a PR today :)

### PR DESCRIPTION
**Pull request by aballano**
Fixes #3 
- Included @IncludeHashEquals annotation to do the opposite work of @IgnoreHashEquals.
- Created lib's annotation so clients don't have to implement their own (@REggar should I do the same for @IgnoreHashEquals?)

P.S. Please add a Hacktoberfest label :)

### CODE REVIEW

**Comment by aballano** [comment]
@REggar Dunno if duplicating the extension class with different behavior is better than adding that logic to the original `AutoValueIgnoreHashEqualsExtension` class since adding the logic there could allow to check whether only _one_ annotation type is present, any thoughts?

**Comment by REggar** [comment]
If we were to include annotations it should be in a separate dependancy (see https://github.com/google/auto/issues/268), so I would like to add this as a later enhancement.

I agree with you that in terms of duplicating the class, I'd rather have them combined for now. This reduces the need for any duplicate code (generation of hashCode/equals implementations) and as you said will allow us to show some sort of meaningful error if both `@IgnoreHashEquals` and `@IncludeHashEquals` are used within in the same class.

**Comment by aballano** [comment]
@REggar Changes done!

**Review by REggar — APPROVED** [review]
Looks great, thanks!

I'll update the documentation and release 1.1.0 with these changes either later today or tomorrow.

**Comment by aballano** [comment]
Glad to help! :)

**Pull request merged**
